// Add to Person a createGreetingsForFriends method which will return an array of strings - each string in the array is a greeting generated by the createGreeting method. For example:
//
// > var alfie = new Person('Alfie');
// > var anushka = new Person('Anushka');
// > var henrique = new Person('Henrique');
// > alfie.addFriend(anushka);
// > alfie.addFriend(henrique);
// > alfie.createGreetingsForFriends();
// ["Yo Anushka! from Alfie.", "Yo Henrique! from Alfie."]
// Do this without using a loop but by using map instead.

class Person {
  constructor(name) {
    this.name = name;
    this.friends = [];
  }

  addFriend(friend) {
    this.friends.push(friend);
  }

  createGreeting(other) {
    return 'Yo ' + other.name + '! from ' + this.name + '.';
  }

  greet(other) {
    console.log(this.createGreeting(other));
  }

  lazyGreet(other) {
    setTimeout(() => {this.greet(other)}, 2000);
  }
}

var p1 = new Person('Shahram');
var p2 = new Person('Sofia');

p1.lazyGreet(p2);
